[package]
name = "cnvtr"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
traq-bot-http = { workspace = true }

bot = { path = "../bot" }
config = { path = "../config" }
model = { path = "../model" }
router = { path = "../router" }
