[package]
name = "cnvtr"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
envy = { workspace = true }
dotenvy = { workspace = true }

tokio = { workspace = true }
axum = { workspace = true }

bot = { path = "../bot" }
repository = { path = "../repository" }
router = { path = "../router" }
traq-client = { path = "../traq-client" }
