[package]
name = "bot-cnvtr"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
dotenvy = "0.15"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.29", features = ["full"] }
traq-bot-http = "0.6"
traq = "0.1"
indoc = "2.0"
thiserror = "1.0"

[dependencies.sqlx]
version = "0.6"
features = ["runtime-tokio-native-tls", "mysql", "migrate"]
