[workspace]
resolver = "2"

members = ["cnvtr", "entity", "repository", "router", "usecases", "traq-client", "wh-handler"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
itertools = "0.11"
indoc = "2.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.3", features = ["v4", "serde"] }

dotenvy = "0.15"
envy = "0.4"
clap = { version = "4.3", features = ["derive"] }
shlex = "1.1"

tokio = { version = "1.29", features = ["full"] }
futures = "0.3"
async-stream = "0.3"
async-trait = "0.1"

axum = "0.7"
reqwest = { version = "0.11", features = ["json", "multipart"] }
hyper = "1.1"

traq-bot-http = { version = "0.8", features = ["uuid"] }
traq = "0.1"

[workspace.dependencies.sqlx]
version = "0.7"
features = ["runtime-tokio", "tls-rustls", "mysql", "migrate", "uuid"]
