[package]
name = "bot-cnvtr"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
tokio = { version = "1.29", features = ["full"] }
traq-bot-http = "0.6"
