[workspace]
resolver = "2"

members = ["cnvtr", "config", "model", "router", "cli", "bot"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
itertools = "0.11"
indoc = "2.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.3", features = ["v4", "serde"] }

dotenvy = "0.15"
envy = "0.4"
clap = { version = "4.3", features = ["derive"] }
shlex = "1.1"

tokio = { version = "1.29", features = ["full"] }
futures = "0.3"
async-stream = "0.3"
async-recursion = "1.0"

axum = "0.6"
reqwest = { version = "0.11", features = ["json", "multipart"] }

traq-bot-http = { version = "0.6", features = ["uuid"] }
traq = "0.1"

[workspace.dependencies.sqlx]
version = "0.6"
features = ["runtime-tokio-native-tls", "mysql", "migrate", "uuid"]
