[package]
name = "router"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
indoc = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

axum = { workspace = true }
hyper = { workspace = true }

traq-bot-http = { workspace = true }
sqlx = { workspace = true }

bot = { path = "../bot" }
model = { path = "../model" }
