[package]
name = "router"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
envy = { workspace = true }
indoc = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

tokio = { workspace = true }
axum = { workspace = true }
hyper = { workspace = true }

traq-bot-http = { workspace = true }
sqlx = { workspace = true }

usecases = { path = "../usecases" }
repository = { path = "../repository" }
traq-client = { path = "../traq-client" }
wh-handler = { path = "../wh-handler" }
