[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }

clap = { workspace = true }

traq-bot-http = { workspace = true }

repository = { path = "../repository" }
