[package]
name = "domain"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
paste.workspace = true
indoc.workspace = true
thiserror.workspace = true
anyhow.workspace = true

serde.workspace = true
uuid.workspace = true

[lints]
workspace = true
