[package]
name = "cron"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tokio-stream = { version = "0.1", features = ["time"] }
tracing.workspace = true

domain.workspace = true

[lints]
workspace = true
