[package]
name = "usecases"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
http.workspace = true
http-body.workspace = true
tower.workspace = true

domain.workspace = true

[lints]
workspace = true
