[package]
name = "usecases"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
http.workspace = true
traq-bot-http.workspace = true

domain.workspace = true

[lints]
workspace = true
