[package]
name = "usecases"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
serde_json.workspace = true

traq-bot-http.workspace = true
sqlx.workspace = true

domain.workspace = true
