[package]
name = "wh-handler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
indoc.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

usecases.path = "../usecases"
