[package]
name = "traq-client"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
itertools.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

reqwest.workspace = true
traq = "0.1"

domain.workspace = true
