name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
          cache: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:release-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: h1rono
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#otherDeps
      - run: nix build .#cargoDeps
      - run: nix build
      - run: nix flake check

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - rust
      - nix
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Collect metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/h1rono/bot-cnvtr
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h1rono
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref_name == 'main' && 'true' || 'false' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  notify-ns:
    runs-on: ubuntu-latest
    needs: [ "ghcr" ]
    if: ${{ github.ref_name == 'main' }}
    env:
      REPOSITORY: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v4
      - run: mkdir ./tmp
      - id: get-hook-id
        run: |
          bash .github/scripts/ns-hook.sh hook-id > ./tmp/hook-id
          echo "result=$(cat ./tmp/hook-id)" >> "$GITHUB_OUTPUT"
      - id: get-delivery-id
        env:
          HOOK_ID: ${{ steps.get-hook-id.outputs.result }}
        run: |
          bash .github/scripts/ns-hook.sh push-delivery-id > ./tmp/delivery-id
          echo "result=$(cat ./tmp/delivery-id)" >> "$GITHUB_OUTPUT"
      - id: get-request
        env:
          HOOK_ID: ${{ steps.get-hook-id.outputs.result }}
          DELIVERY_ID: ${{ steps.get-delivery-id.outputs.result }}
        run: |
          bash .github/scripts/ns-hook.sh delivery-request > ./tmp/delivery.json
          echo "result_file=$(pwd)/tmp/delivery.json" >> "$GITHUB_OUTPUT"
      - id: delivery-neoshowcase
        env:
          DELIVERY_FILE: ${{ steps.get-request.outputs.result_file }}
          NS_ENDPOINT: ${{ secrets.NS_ENDPOINT }}
        run: |
          cat "$DELIVERY_FILE" | bash .github/scripts/ns-hook.sh request "$NS_ENDPOINT"
