name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
          cache: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - rust
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h1rono
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: distroless image
        uses: ./.github/docker-mbp-action
        with:
          push: ${{ github.ref_name == 'main' && 'true' || 'false' }}
          tags: |
            type=ref,event=branch,suffix=
            type=ref,event=pr,suffix=
            type=sha,prefix=,suffix=
            type=ref,event=branch,suffix=-distroless
            type=ref,event=pr,suffix=-distroless
            type=sha,prefix=,suffix=-distroless
          target: server-distroless
          cache: "true"
      - name: debian-slim image
        uses: ./.github/docker-mbp-action
        with:
          push: ${{ github.ref_name == 'main' && 'true' || 'false' }}
          tags: |
            type=ref,event=branch,suffix=-debian-slim
            type=ref,event=pr,suffix=-debian-slim
            type=sha,prefix=,suffix=-debian-slim
          target: server-debian-slim
          cache: "true"
