name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
          cache: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:release-23.11
      - name: Setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: h1rono
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build @1
        run: nix build .#otherDeps
      - name: Build @2
        run: nix build .#cargoDeps
      - name: Build @3
        run: nix build
      - name: Build @4
        run: |
          nix build .#releaseImage
          cp result bot-cnvtr.tar.gz
      - name: Checks
        run: nix flake check
      - name: Upload release image
        uses: actions/upload-artifact@v4
        with:
          name: cnvtr-nix-image
          path: ./bot-cnvtr.tar.gz

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - rust
      - nix
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Collect metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/h1rono/bot-cnvtr
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h1rono
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref_name == 'main' && 'true' || 'false' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ghcr-nix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - rust
      - nix
    if: ${{ github.ref_name == 'main' }}
    env:
      REPOSITORY: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: cnvtr-nix-image
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h1rono
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load image
        run: |
          docker load < bot-cnvtr.tar.gz
          rm bot-cnvtr.tar.gz
      - name: Rename image
        run: |
          docker image ls --format json bot-cnvtr:latest | jq -r -e '.ID' > image_id
          docker image tag "$(cat image_id)" ghcr.io/h1rono/bot-cnvtr:nix-latest
          docker image rm bot-cnvtr:latest
          rm image_id
      - name: Push image
        run: docker push ghcr.io/h1rono/bot-cnvtr:nix-latest

  notify-ns:
    runs-on: ubuntu-latest
    needs: [ "ghcr" ]
    if: ${{ github.ref_name == 'main' }}
    env:
      REPOSITORY: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: mkdir ./tmp
      - name: Get webhook ID
        id: get-hook-id
        run: |
          bash .github/scripts/ns-hook.sh hook-id > ./tmp/hook-id
          echo "result=$(cat ./tmp/hook-id)" >> "$GITHUB_OUTPUT"
      - name: Get delivery ID
        id: get-delivery-id
        env:
          HOOK_ID: ${{ steps.get-hook-id.outputs.result }}
        run: |
          bash .github/scripts/ns-hook.sh push-delivery-id > ./tmp/delivery-id
          echo "result=$(cat ./tmp/delivery-id)" >> "$GITHUB_OUTPUT"
      - name: Get delivery contents
        id: get-request
        env:
          HOOK_ID: ${{ steps.get-hook-id.outputs.result }}
          DELIVERY_ID: ${{ steps.get-delivery-id.outputs.result }}
        run: |
          bash .github/scripts/ns-hook.sh delivery-request > ./tmp/delivery.json
          echo "result_file=$(pwd)/tmp/delivery.json" >> "$GITHUB_OUTPUT"
      - name: Deliver NeoShowcase
        id: delivery-neoshowcase
        env:
          DELIVERY_FILE: ${{ steps.get-request.outputs.result_file }}
          NS_ENDPOINT: ${{ secrets.NS_ENDPOINT }}
        run: |
          cat "$DELIVERY_FILE" | bash .github/scripts/ns-hook.sh request "$NS_ENDPOINT"
