name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Collect metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/h1rono/bot-cnvtr
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h1rono
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
