name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: h1rono
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: distroless image
        uses: ./.github/docker-mbp-action
        with:
          push: true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}-distroless
            type=semver,pattern={{major}}.{{minor}}-distroless
          target: server-distroless
          cache: "false"
      - name: debian-slim image
        uses: ./.github/docker-mbp-action
        with:
          push: true
          tags: |
            type=semver,pattern={{version}}-debian-slim
            type=semver,pattern={{major}}.{{minor}}-debian-slim
          target: server-debian-slim
          cache: "false"
