name: Update flake.lock

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: "nixpkgs=channel:release-23.11"
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          pr-title: ":arrow_up: CI: update flake"
          git-author-name: "H1rono"
          git-author-email: "54711422+H1rono@users.noreply.github.com"
          git-committer-name: "H1rono"
          git-committer-email: "54711422+H1rono@users.noreply.github.com"
          token: ${{ secrets.PAT }}
          pr-assignees: H1rono
